name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  ACTIVE_API_URL: https://noname.lab/active
  ACTIVE_SEVERITY_THRESHOLD: medium
  ACTIVE_TEST_SUITE_ID: 62f5921c-d200-4f6f-a104-29674ad30a94
  ACTIVE_BASE_URL: 'http://192.168.38.234:5002/' # empty by default use the source URL

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Run VAmPI
      run: docker compose up -d

    - name: Test VAmPI
      run: sleep 5 && curl http://192.168.38.234:5002/ --retry 10 --retry-delay 1

  scan:
    runs-on: self-hosted
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: ${{ secrets.ACTIVE_REGISTRY_USER }}
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: security test
        run: |
          docker run \
          --add-host=host.docker.internal:host-gateway \
          -e ACTIVE_CONFIG_FILE_PATH=/noname/config.json \
          -v $(pwd)/noname:/noname \
          -v $(pwd)/openapi_specs:/openapi_specs \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:2.0.0 scan \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} \
          --severity-threshold=medium \
          --branch-name=master \
          --log-level=error \
          --api-url=${{ env.ACTIVE_API_URL }} \
          --test-group-id=${{ env.ACTIVE_TEST_SUITE_ID }}

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello World! ${{ env.ACTIVE_BASE_URL }}