name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  ACTIVE_API_URL: https://noname.local/active
  ACTIVE_SEVERITY_THRESHOLD: medium
  ACTIVE_TEST_SUITE_ID: f9caf5be-c832-4341-8cac-4b6672432048
  ACTIVE_BASE_URL: 'http://localhost:5002/' # empty by default use the source URL

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Run VAmPI
      run: docker compose up -d

    - name: Test VAmPI
      run: sleep 5 && curl http://localhost:5002/ --retry 10 --retry-delay 1

  scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: ${{ secrets.ACTIVE_REGISTRY_USER }}
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: security test
        run: |
          docker run \
          -e ACTIVE_CONFIG_FILE_PATH=/noname/config.json \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:2.0.0 \
          scan \
          --api-url=${{ env.ACTIVE_BASE_URL }} \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} \
          --severity-threshold=medium \
          --base-url=http://localhost:5002 \
          --branch-name=master \
          --log-level=debug

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello world- ${{ env.ACTIVE_BASE_URL }}